### ISSUE TITLE
RuntimeError: GpuCorrMM failed to allocate working memory of 576 x 802816

### ISSUE THREAD

**Issue by huangh12** [DavideA/dilation-keras#1]
Hello.  Thx for your code. I encountered a problem when runming on my machine.  As the image shows below.
![default](https://cloud.githubusercontent.com/assets/18748036/23611033/3c7a7c36-02b0-11e7-9f4c-b11933a8bdc7.png)
I've tryed to search and fix this problem for long time but failed.  Have you ever got this error, could you please help? Thank you in advance!

**Comment by huangh12** [comment]
![default](https://cloud.githubusercontent.com/assets/18748036/23611014/18d8a3b6-02b0-11e7-9ce7-05725ad02df8.png)

**Comment by DavideA** [comment]
Hi. 

I'm afraid your GPU features too low memory. What model is it?
Does it fail on all datasets/networks?

**Comment by huangh12** [comment]
Yes, DavideA you're right. I run the voc dataset and the problem lies in my gpu's lack of memory (It's only 2G and can't load in the network parameters).  After change into cpu mode, the error disappeared.  

I have to say, your code really helped me a lot for the comprehension of the original paper. You implemented the 

> front-end(VGG16 with removal of last two pooling layer)+dilation7/dilation8(basic and large module)/dilation10

respectively in very details. But there are still some questions leaved for you: 

one tiny question is, you seems havn't used the input shape as the paper descriped for all the four dataset. Can you explain the reason.

second one: although with the comment, I still can't understand the line74-line75. Why these two layers exist? I found no evidence  descriped in the paper. Some more explaination will be appreciated.
![default](https://cloud.githubusercontent.com/assets/18748036/23671715/323d93c8-03a7-11e7-969b-41b7dbf8ee76.png)

Thank you in advance!

**Comment by DavideA** [comment]
Glad I could help!

1) Input shapes: the one I used are taken from authors' [original prototxt files](https://github.com/fyu/dilation/tree/master/models).

2) That couple of layers (as the above comments state) pretend to be a deconvolution layer (aka transposed convolution). You can find such deconv layer in the [cityscapes prototxt](https://github.com/fyu/dilation/blob/master/models/dilation10_cityscapes_deploy.prototxt) at lines 690-707. I tried to port such layer as a keras deconvolution2d layer but I never managed to get it to work. Looking to the weights, you'll see they're a 16x16 gaussian (i.e. it's just an upsampling). So I implemented it as an upsampling followed by a gaussian convolution. It is not the same thing, but it should be very similar.

Bye!

**Comment by huangh12** [comment]
It's really helpful. Thank you very much :)

**Comment by DavideA** [comment]
You're welcome!

Closed
