### ISSUE TITLE
Run demo prediction

### ISSUE THREAD

**Issue by delhomer** [DavideA/dilation-keras#3]
Hi @DavideA ,
Thanks for your dilated convolution implementation! That's a precious work, as such a model is harder to master than other semantic segmentation architectures.

I am currently looking at your code, and I was wondering how to run a simple prediction. I just ran `python predict.py`, as suggested by your `README` file. However, I get a value error as follows:
```
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv1_2/convolution' (op: 'Conv2D') with input shapes: [?,1,1394,64], [3,3,64,64].
```

Am I missing something?
I ran it into a virtual env with following package versions:
- tensorflow 1.6.0
- keras 2.1.5

Thank you for your contribution!

**Comment by ifahim** [comment]
getting same issue. 
tensorflow==1.9.0
Keras==2.2.2

**Comment by DavideA** [comment]
This code is starting to get old.

It was tested with Keras 1.2.2 and Theano as backend.
Can you share me what your keras.json is like?

**Comment by ifahim** [comment]
Right now it contains only backend info.  
~/.keras$ vim keras.json 

{
    "backend": "tensorflow"
}

should i put any other information?
Thanks

**Comment by DavideA** [comment]
I'd try a

"image_data_format": "channels_last"

Not sure that's the problem.

**Comment by delhomer** [comment]
@DavideA actually it does not work with "image_data_format": "channels_last". However you highlight the good point: we must specify "image_data_format": "channels_first". Thanks for your answer!

I close the issue as it seems solved.
